# Universal Functions

NumPy provides some useful out of the box functions to perform operations on matrices. These functions are divided into 2 different segments:
1. Unary Functions
2. Binary Functions

A Unary function operates on a single matrix by itself, while a binary function requires 2 matrices. 

# Unary Functions

## np.sqrt
This function simply returns square root of all the elements in an array.

In [1]:
import numpy as np
a = np.array([[4,9,16],
              [25,36,49]])

np.sqrt(a)

array([[2., 3., 4.],
       [5., 6., 7.]])

## np.exp
This function computes the exponent of each element in an array.

In [2]:
np.exp(a)

array([[5.45981500e+01, 8.10308393e+03, 8.88611052e+06],
       [7.20048993e+10, 4.31123155e+15, 1.90734657e+21]])

## np.log
This function will compute the natural logarithm (base e) of each element in an array. 

In [3]:
np.log(a)

array([[1.38629436, 2.19722458, 2.77258872],
       [3.21887582, 3.58351894, 3.8918203 ]])

Similarly, we can also use **log10, log2, logp**.

## np.rint
This function rounds elements to their nearest integer. The function `rint` can be read as `Round to Integer`

In [4]:
a = np.array([[1.38629436, 2.19722458, 2.77258872],
       [3.21887582, 3.58351894, 3.8918203 ]])
np.rint(a)

array([[1., 2., 3.],
       [3., 4., 4.]])

![](./images/ufuncs.JPG)

# Binary Functions

Lets start with 2 matrices and perform some basic arithmatic operations on them. 

In [5]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[2,4,8],
              [16,32,64]])

## Addition

In [6]:
a+b

array([[ 3,  6, 11],
       [20, 37, 70]])

## Subtraction

In [7]:
a-b

array([[ -1,  -2,  -5],
       [-12, -27, -58]])

## Multiplication

In [8]:
a*b

array([[  2,   8,  24],
       [ 64, 160, 384]])

## Division

In [9]:
a/b

array([[0.5    , 0.5    , 0.375  ],
       [0.25   , 0.15625, 0.09375]])

There are several binary functions that one can choose from. The table below shows some of the binary function operations available.

> Keep in mind that the matrices have to always be of appropriate size for the binary operation to work. We cannot add a (2,2) matrix to a (3x3) matrix. If you can perform the matrix operation mathematically, then the system can also perform it for you. But it will fail on attempting an invalid matrix operation.


![](./images/binary_funcs.JPG)